user:
  flops_per_cycle: 32
  clock_frequency_type: static
  clock_frequency_hz: 1e+09
  distance_lat_ns:
    - [67.9, 136.4]
    - [137.4, 68.8]
  distance_bw_gbps:
    - [120875, 34472]
    - [34471.5, 120849]

workflow:
  execs_count: 6
  reads_count: 6
  writes_count: 6

runtime:
  threads_checksum: 0
  threads_active: 0
  tasks_active_count: 6
  reads_active_count: 6
  writes_active_count: 6
  core_availability:
    0: {avail_until: 313.064}
    1: {avail_until: 626.445}
    2: {avail_until: 626.279}
    3: {avail_until: 626.114}
    4: {avail_until: 939.261}
    5: {avail_until: 938.764}
    6: {avail_until: 0}
    7: {avail_until: 0}
    24: {avail_until: 0}
    25: {avail_until: 0}
    26: {avail_until: 0}
    27: {avail_until: 0}
    28: {avail_until: 0}
    29: {avail_until: 0}
    30: {avail_until: 0}
    31: {avail_until: 0}

trace:
  name_to_thread_locality:
    v6: {numa_id: 0, core_id: 5, voluntary_cs: 0, involuntary_cs: 0, core_migrations: 0}
    v5: {numa_id: 0, core_id: 4, voluntary_cs: 0, involuntary_cs: 0, core_migrations: 0}
    v4: {numa_id: 0, core_id: 3, voluntary_cs: 0, involuntary_cs: 0, core_migrations: 0}
    v3: {numa_id: 0, core_id: 2, voluntary_cs: 0, involuntary_cs: 0, core_migrations: 0}
    v2: {numa_id: 0, core_id: 1, voluntary_cs: 0, involuntary_cs: 0, core_migrations: 0}
    v1: {numa_id: 0, core_id: 0, voluntary_cs: 0, involuntary_cs: 0, core_migrations: 0}

  numa_mappings_write:
    v4->v6: {numa_ids: [0]}
    v3->v5: {numa_ids: [0]}
    v2->v5: {numa_ids: [0]}
    v1->v4: {numa_ids: [0]}
    v1->v3: {numa_ids: [0]}
    v1->v2: {numa_ids: [0]}

  numa_mappings_read:
    v4->v6: {numa_ids: [0]}
    v3->v5: {numa_ids: [0]}
    v2->v5: {numa_ids: [0]}
    v1->v4: {numa_ids: [0]}
    v1->v3: {numa_ids: [0]}
    v1->v2: {numa_ids: [0]}

  comm_name_read_offsets:
    v4->v6: {start: 626.114, end: 626.264, payload: 1e+07}
    v3->v5: {start: 626.445, end: 626.678, payload: 2e+07}
    v2->v5: {start: 626.445, end: 626.761, payload: 3e+07}
    v1->v4: {start: 313.064, end: 313.463, payload: 4e+07}
    v1->v3: {start: 313.064, end: 313.546, payload: 5e+07}
    v1->v2: {start: 313.064, end: 313.629, payload: 6e+07}

  comm_name_write_offsets:
    v4->v6: {start: 625.963, end: 626.114, payload: 1e+07}
    v3->v5: {start: 626.046, end: 626.279, payload: 2e+07}
    v2->v5: {start: 626.129, end: 626.445, payload: 3e+07}
    v1->v4: {start: 312.5, end: 312.899, payload: 4e+07}
    v1->v3: {start: 312.5, end: 312.982, payload: 5e+07}
    v1->v2: {start: 312.5, end: 313.064, payload: 6e+07}

  exec_name_compute_offsets:
    v6: {start: 626.264, end: 938.764, payload: 1e+07}
    v5: {start: 626.761, end: 939.261, payload: 1e+07}
    v4: {start: 313.463, end: 625.963, payload: 1e+07}
    v3: {start: 313.546, end: 626.046, payload: 1e+07}
    v2: {start: 313.629, end: 626.129, payload: 1e+07}
    v1: {start: 0, end: 312.5, payload: 1e+07}

  exec_name_total_offsets:
    v6: {start: 626.114, end: 938.764, payload: 1e+07}
    v5: {start: 626.445, end: 939.261, payload: 1e+07}
    v4: {start: 313.064, end: 626.114, payload: 1e+07}
    v3: {start: 313.064, end: 626.279, payload: 1e+07}
    v2: {start: 313.064, end: 626.445, payload: 1e+07}
    v1: {start: 0, end: 313.064, payload: 1e+07}

