export SIMGRID_PREFIX=/opt/simgrid
export PATH=$SIMGRID_PREFIX/bin:$PATH
export PKG_CONFIG_PATH=$SIMGRID_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH
export LIBRARY_PATH=$SIMGRID_PREFIX/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=$SIMGRID_PREFIX/lib:$LD_LIBRARY_PATH
export CPATH=$SIMGRID_PREFIX/include:$CPATH